### ISSUE TITLE
[feature] mark diff in line number area

### ISSUE THREAD

**Issue by liyechen** [ngemily/vim-vp4#29]
Hi, is it possible to add the feature to mark the diff in line area?
- mark the line number to green if this line is added
- mark the line number to blue if this line is modified
- add a red mark if there are some lines deleted here

like some git plugin

**Comment by ngemily** [comment]
Hi there,

Thanks for your interest in vp4!  At this time, no plans to implement this.  Personally, I use mhinz/vim-signify to provide gutter symbols; it works with perforce.

Thanks,
Emily

**Comment by liyechen** [comment]
> Hi there,
> 
> Thanks for your interest in vp4! At this time, no plans to implement this. Personally, I use mhinz/vim-signify to provide gutter symbols; it works with perforce.
> 
> Thanks,
> Emily

Thank you for your advice. It really helped me.
